= project-archetype

Project archetype for Teragrep projects.

The `pom.xml` examples are added to the main `pom.xml` file under `<plugins>..</plugins>` section.

== Mandatory plugins for java projects

=== checkstyle

Enforces certain coding standards, complements both `enforcer` and `formatter` plugins

=== enforcer

The enforcer plugin forces certain standards in pom.xml

=== formatter (spotless)

Will enforce and can automatically apply proper formatting and licensing information to project files.

Also known as `spotless`

=== rat

The rat plugin is used to enforce existence of correct licenses, will complement formatter plugin

== Other java project plugins

=== jacoco

Provides test coverity reports.

=== equalsverifier

The equals verifier dependency is used in tests to verify whether equals and hashcode overrides are implemented correctly

=== testcontainers

Provides containers for testing use. No need to rely on manually installed and configured external services.

== Other files

=== workflows

Contains fully reusable templates or otherwise useful boilerplate for GitHub workflows

=== example-java-project

Contains example java project that uses mandatory plugins as described above

=== rpm-packaging

Contains minimal example java project for link:workflows#upload_release_github_attachmentyaml[upload_release_github_attachment.yaml] that builds the java project and packages it to `.rpm` file, ready to be attached to the release.
