= Example RPM packaging project

The goal of this project is to be a minimal example demo for link:../workflows#upload_release_github_attachmentyaml[upload_release_github_attachment.yaml]. The link:rpm/rpm.pom.xml[rpm/rpm.pom.xml] contains examples on how to include the built java artifact from `target/example-rpm-project.jar` and auxiliary files from `rpm/aux/` to different locations with different permissions.

== Manual building

You can build the java artifacts with `mvn clean package` on repository root. This should give you `target/example-rpm-project.jar` file that will be packaged inside the `.rpm`.

You can build the `.rpm` by first changing to the `rpm` directory with `cd rpm/` and then running the following commands:
.Creating a RPM with necessary GPG-signing secrets
[source]
----
export RPM_SIGNING_PASSPHRASE="Replace-With-Your-GPG-Passphrase";
export RPM_SIGNING_KEYNAME="Replace-With-Your-GPG-Keyname";
mvn clean package -f rpm.pom.xml
----

This will create and sign a `.rpm` file under `target/rpm/com.teragrep-example-rpm-project/RPMS/noarch/` that contains the java artifact and any files under `aux/` directory.

You can verify it has been properly signed with the following command: `rpm --query --package --info path/to/the/example-rpm-project.rpm`

It can warn about `NOKEY` if created GPG key is not imported to the system.

.Partial output of `rpm --query --package --info example-rpm-project.rpm`
[source]
----
Signature   :
              RSA/SHA512, Fri 20 Feb 2026 10:18:21 AM EET, Key ID abcdef1234567890
----

You can observe the contents of the produced `.rpm` with the following command: `rpm --query --package --list --verbose path/to/the/example-rpm-project.rpm`.

The file listing should look like this:

.Output of `rpm --query --package --list --verbose example-rpm-project.rpm`
[source]
----
drw-r--r--    2 root     root         0 Feb 19 14:36 /opt/teragrep/example-rpm-project/aux
-rw-r--r--    1 root     root        56 Feb 19 14:36 /opt/teragrep/example-rpm-project/aux/extra-aux-file.txt
drwxr-xr-x    2 root     root         0 Feb 19 14:36 /opt/teragrep/example-rpm-project/lib
-rwxr-xr-x    1 root     root      2435 Feb 19 14:32 /opt/teragrep/example-rpm-project/lib/example-rpm-project.jar
----