on:
  push:
jobs:
  publish:
    runs-on: ubuntu-latest
    # This is mvn_01 specific part
    defaults:
      run:
        shell: bash
        working-directory: ./example-javadoc-doxygen-project
    # End of mvn_01 specific part
    permissions:
      contents: write
    steps:
      # Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Cache
      - name: Cache Local Maven Repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      # Setup java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'adopt'
      # Used for docs output
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      # Make dirs
      - name: Make dirs
        run: mkdir -p docs/${{steps.extract_branch.outputs.branch}}/
      # Install dependencies
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install doxygen graphviz plantuml
      # Generate doxygen docs
      - name: Generate Doxygen docs
        run: doxygen Doxyfile && mv "target/doxygen/html" "docs/${{steps.extract_branch.outputs.branch}}/doxygen/"
        env:
          OUTPUT_DIRECTORY: "target/doxygen"
      # Run javadoc and generate war containing both doxygen and javadoc
      - name: Generate javadoc and create combined javadoc/doxygen war
        run: mvn --batch -Drevision="${{steps.extract_branch.outputs.branch}}-${{github.sha}}" -Dchangelist='' -Dsha1="" -DwarSourceDirectory=docs/${{steps.extract_branch.outputs.branch}}/ javadoc:aggregate war:war && mv target/site/apidocs "docs/${{steps.extract_branch.outputs.branch}}/javadoc/" && mv target/*.war "docs/${{steps.extract_branch.outputs.branch}}/"
        env:
          MAVEN_OPTS: "-Dmaven.javadoc.failOnError=false"
      # Deploy
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # This is mvn_01 specific path
          folder: example-javadoc-doxygen-project/docs/${{steps.extract_branch.outputs.branch}}/
          #       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          # /End of mvn_01 specific path
          target-folder: docs/${{steps.extract_branch.outputs.branch}}/
          token: ${{ secrets.GITHUB_TOKEN }}
