name: Lint GitHub Actions workflows
on: [push]

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run actionlint
        run: docker run --rm -v $(pwd)/workflows:/repo --workdir /repo rhysd/actionlint:latest -color
