name: Lint GitHub Actions workflows
on: [push]

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run actionlint
        run:
          for workflow in ci coverity publish_pages_from_docs upload_release_github_attachment upload_release_github_packages upload_release_maven_central; do
            docker run --rm -v $(pwd)/workflows:/repo --workdir /repo rhysd/actionlint:latest -color /repo/${workflow}.yaml;
          done;
            
